/**
 * 01.scripts/1.2/1.2.3.3/easyflow-admin-oracle-1.2.3.3-ddl-iteration.sql
 * */

-- ----------------------------
-- TABLE STRUCTURE FOR EASYFLOW_LOCAL_TX_DEFINE
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_LOCAL_TX_DEFINE'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_LOCAL_TX_DEFINE';
end   if;
end;
/
CREATE TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"
(
    "LOCAL_TX_ID"      NVARCHAR2(32) NOT NULL,
    "FLOW_DETAIL_ID"   NVARCHAR2(32) NOT NULL,
    "FLOW_ID"          NVARCHAR2(32) NOT NULL,
    "NAME"             NVARCHAR2(64) NOT NULL,
    "TOTAL_TIMEOUT"    NUMBER(11) NOT NULL,
    "EXCEPTION_CONF"   NCLOB NOT NULL,
    "COMPONENT_DETAIL" NCLOB NOT NULL,
    "OPERATOR_ID"      NVARCHAR2(32) NOT NULL,
    "CREATE_TIME"      DATE  NOT NULL,
    "UPDATE_TIME"      DATE,
    "DELETED"          NUMBER(20) NOT NULL
)
;
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."LOCAL_TX_ID" IS '本地事务ID';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."FLOW_DETAIL_ID" IS '流程版本详情ID';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."FLOW_ID" IS '流程ID';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."NAME" IS '事务显示名称';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."TOTAL_TIMEOUT" IS '事务总超时时间(秒), 0 不限制';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."EXCEPTION_CONF" IS '事务异常配置';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."COMPONENT_DETAIL" IS '事务内具体组件详情';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."OPERATOR_ID" IS '操作人ID';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"."DELETED" IS 'NORMAL:0, DELETED: DELETED TIMESTAMP';
COMMENT
    ON TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE" IS '流程版本事务定义';



-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE EASYFLOW_LOCAL_TX_DEFINE
-- ----------------------------
ALTER TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE"
    ADD PRIMARY KEY ("LOCAL_TX_ID");

-- ----------------------------
-- INDEXES STRUCTURE FOR TABLE EASYFLOW_LOCAL_TX_DEFINE
-- ----------------------------
CREATE INDEX "IDX_LTX_FLOW_DETAIL_ID"
    ON "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE" ("FLOW_DETAIL_ID");
CREATE INDEX "IDX_LTX_FLOW_ID"
    ON "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE" ("FLOW_ID");
CREATE INDEX "IDX_LTX_CREATE_TIME"
    ON "EASYFLOW_3052TJBHDEV"."EASYFLOW_LOCAL_TX_DEFINE" ("CREATE_TIME");


/**
 * 
 * 01.scripts/1.2/1.2.3.4/easyflow-admin-oracle-1.2.3.4-ddl-iteration.sql
 * */
ALTER TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_FLOW_DETAIL_REC"
    ADD "NO_LOG_NODE" NCLOB NULL
    ADD "NO_LOG_VAR" NCLOB NULL ;
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_FLOW_DETAIL_REC"."NO_LOG_NODE" IS '不打印日志流程组件 SRCID 列表';
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_FLOW_DETAIL_REC"."NO_LOG_VAR" IS '不输出日志流程变量 KEY 列表';


ALTER TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_FLOW_ENV_RELATION"
    ADD "LOG_LEVEL" NVARCHAR2(5) NULL;
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_FLOW_ENV_RELATION"."LOG_LEVEL" IS '流程日志级别 TRACE,DEBUG,INFO,WARN,ERROR';


ALTER TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_API_ROUTE_CONFIG"
    ADD "API_BIZ_TYPE" NVARCHAR2(2) DEFAULT '01';
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_API_ROUTE_CONFIG"."API_BIZ_TYPE" IS '01 表示交易接口,02 表示查询接口';

/**
 * 
 * 01.scripts/1.2/1.2.3.5/easyflow-admin-oracle-1.2.3.5-ddl-iteration.sql
 * */

-- ----------------------------
-- 更新时间：2021/12/17
-- 负责人：李仁会
-- 更新内容：设置实例清理时间功能涉及表修改
-- ----------------------------

ALTER TABLE "EASYFLOW_3052TJBHDEV".EASYFLOW_FLOW_ENV_RELATION
    ADD FLOW_INSTANCE_CLEAR_TIME NUMBER(20) NULL;
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV".EASYFLOW_FLOW_ENV_RELATION.FLOW_INSTANCE_CLEAR_TIME IS '实例清理时间,单位秒';
----------------------------------------
----------------------------------------
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV".EASYFLOW_FLOW_ENV_RELATION.WORK_STATUS IS '工作状态 FlowEnvWorkStatus(001-运行中, 002-停止运行,003-灰度中)';
-- ----------------------------
-- 更新时间：2021/12/20
-- 负责人：李仁会
-- 更新内容：流程图区分交易和查询
-- ----------------------------

ALTER TABLE "EASYFLOW_3052TJBHDEV".EASYFLOW_FLOW_DEFINE
    ADD BIZ_TYPE CHAR(2) NULL;
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV".EASYFLOW_FLOW_DEFINE.BIZ_TYPE IS '业务类型 BizType(01-交易, 02-查询)';


-- ----------------------------
-- 更新时间：2021/12/22
-- 负责人：李杰
-- 更新内容：项目,环境,集群id 关联变更

-- cluster_id 为空时数据填充无效集群id DML

UPDATE "EASYFLOW_3052TJBHDEV".EASYFLOW_ENV
SET CLUSTER_ID=CONCAT('empty-', substr(cast(dbms_random.value as varchar2(38)), 3, 20))
WHERE CLUSTER_ID = ''
   OR CLUSTER_ID IS NULL;
-- ----------------------------
-- 更新时间：2021/12/22
-- 负责人：李杰
-- 更新内容：项目,环境,集群id 关联变更
--------------------------------------------
-- 项目编号 集群id 设为必填

ALTER TABLE "EASYFLOW_3052TJBHDEV".EASYFLOW_ENV
    MODIFY (PROJECT_CODE NOT NULL);


ALTER TABLE "EASYFLOW_3052TJBHDEV".EASYFLOW_ENV
    MODIFY (CLUSTER_ID NOT NULL);

--  一个项目下仅允许一个集群,集群可以跨项目共享
ALTER TABLE "EASYFLOW_3052TJBHDEV".EASYFLOW_ENV
    ADD CONSTRAINT UK_EE_PC UNIQUE (PROJECT_CODE, CLUSTER_ID);



/**
 * 01.scripts/1.2/1.2.3.5/easyflow-admin-oracle-1.2.3.5-ddl-iteration2.sql
 * */
--------------------------------------------------------
-- 灰度发布相关新增表
--------------------------------------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_FLUX_RULE'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_FLUX_RULE';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"
(
    "FLUX_RULE_ID"   NVARCHAR2(32) NOT NULL,
    "FLUX_GROUP_ID"  NVARCHAR2(32) NOT NULL,
    "PLAN_ID"        NVARCHAR2(255) NOT NULL,
    "PARAMETER_TYPE" NVARCHAR2(2) NOT NULL,
    "PARAMETER_NAME" NVARCHAR2(32) NOT NULL,
    "OPERATOR"       NVARCHAR2(2) NOT NULL,
    "EXPECT_VALUE"   NVARCHAR2(32) NOT NULL,
    "DELETED"        INTEGER DEFAULT (0) NOT NULL,
    "CREATOR_ID"     NVARCHAR2(32) NOT NULL,
    "CREATE_TIME"    DATE                NOT NULL,
    "UPDATE_TIME"    DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."FLUX_RULE_ID" IS '规则id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."FLUX_GROUP_ID" IS '规则组id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."PARAMETER_TYPE" IS '参数类型 01 req.cookie 02 req.header 03 req.parameter,04 sessionContext';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."PARAMETER_NAME" IS '字段名,字段路径';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."OPERATOR" IS '运算符';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."EXPECT_VALUE" IS '字段比较值';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_FLUX_RULE" IS '上下文流控规则';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_FLUX_RULE
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_FLUX_RULE
    ADD CONSTRAINT "PK_EFR_FLUXRULEID_TNTID" PRIMARY KEY ("FLUX_RULE_ID");


CREATE UNIQUE INDEX EASYFLOW_3052TJBHDEV."UK_EFR_FGPP_D"
    ON EASYFLOW_3052TJBHDEV.EASYFLOW_FLUX_RULE ("FLUX_GROUP_ID" ASC, "PARAMETER_TYPE" ASC, "PARAMETER_NAME" ASC, "DELETED" ASC) TABLESPACE BASE;
---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_JAR_FILE'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_JAR_FILE';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"
(
    "JAR_FILE_ID"        NVARCHAR2(32) NOT NULL,
    "DELETED"            INTEGER NOT NULL,
    "SERVICE_VERSION_ID" NVARCHAR2(32) NOT NULL,
    "GROUP_ID"           NVARCHAR2(64) NOT NULL,
    "ARTIFACT_ID"        NVARCHAR2(64) NOT NULL,
    "ARTIFACT_VERSION"   NVARCHAR2(64) NOT NULL,
    "CHECKSUM_SHA1"      NVARCHAR2(64),
    "CHECKSUM_MD5"       NVARCHAR2(64),
    "STORE_TYPE"         NVARCHAR2(2) NOT NULL,
    "STORE_PATH"         NVARCHAR2(1024) NOT NULL,
    "CREATOR_ID"         NVARCHAR2(32),
    "CREATE_TIME"        DATE,
    "MODIFIER_ID"        NVARCHAR2(32),
    "UPDATE_TIME"        DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."JAR_FILE_ID" IS '依赖文件id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."SERVICE_VERSION_ID" IS '依赖信息id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."GROUP_ID" IS 'maven groupId';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."ARTIFACT_ID" IS 'maven artifactId';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."ARTIFACT_VERSION" IS '依赖版本';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."CHECKSUM_SHA1" IS 'sha1_checksum';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."CHECKSUM_MD5" IS 'md5_checksum';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."STORE_TYPE" IS '文件存储类型 01 sftp 02 oss 03 本地磁盘';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."STORE_PATH" IS '文件存储路径, sftp , oss ,本地磁盘';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."MODIFIER_ID" IS '更新人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_JAR_FILE" IS '流程编排依赖文件表';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_JAR_FILE
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_JAR_FILE
    ADD CONSTRAINT "PK_EJF_JARFILEID_TNTID" PRIMARY KEY ("JAR_FILE_ID");

---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RELEASE_PLAN'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_PLAN';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"
(
    "PLAN_ID"              NVARCHAR2(32) NOT NULL,
    "DELETED"              INTEGER NOT NULL,
    "PROJECT_CODE"         NVARCHAR2(32) NOT NULL,
    "PLAN_NAME"            NVARCHAR2(255) NOT NULL,
    "PLAN_STATUS"          NVARCHAR2(2),
    "UPGRADE_DISPATCHER"   INTEGER NOT NULL,
    "DISPATCHER_VERSION"   NVARCHAR2(64),
    "UPGRADE_ACTUATOR"     INTEGER NOT NULL,
    "ACTUATOR_VERSION"     NVARCHAR2(64),
    "ACTUATOR_RANGE"       NCLOB,
    "ACTUATOR_JAR_LIST"    NCLOB,
    "UPGRADE_SERVICE"      INTEGER NOT NULL,
    "SERVICE_VERSION_LIST" NCLOB,
    "UPGRADE_FLOW"         INTEGER NOT NULL,
    "CREATOR_ID"           NVARCHAR2(32),
    "CREATE_TIME"          DATE,
    "MODIFIER_ID"          NVARCHAR2(32),
    "UPDATE_TIME"          DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."PLAN_ID" IS '计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."PROJECT_CODE" IS '项目 code';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."PLAN_NAME" IS '发布计划名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."PLAN_STATUS" IS '计划状态,01:未发布,02:已发布';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."UPGRADE_DISPATCHER" IS '是否升级调度器,1:是,0:否';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."DISPATCHER_VERSION" IS '调度器版本';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."UPGRADE_ACTUATOR" IS '是否升级执行器,1:是,0:否';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."ACTUATOR_VERSION" IS '执行器版本';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."ACTUATOR_RANGE" IS '执行器升级范围,服务名列表,JSONArray';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."ACTUATOR_JAR_LIST" IS '依赖文件id 列表 JSONArray';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."UPGRADE_SERVICE" IS '是否升级服务,1:是,0:否';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."SERVICE_VERSION_LIST" IS '服务版本信息id列表,JSONArray';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."UPGRADE_FLOW" IS '是否升级流程图';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."MODIFIER_ID" IS '更新人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN" IS '发布计划信息表';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RELEASE_PLAN
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_PLAN
    ADD CONSTRAINT "PK_ERP_PLANID_TNTID" PRIMARY KEY ("PLAN_ID");


CREATE UNIQUE INDEX EASYFLOW_3052TJBHDEV."UK_ERP_PP_D"
    ON EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_PLAN ("PROJECT_CODE" ASC, "PLAN_NAME" ASC, "DELETED" ASC) TABLESPACE BASE;



-- ----------------------------
-- Table structure for EASYFLOW_RELEASE_PLAN_FLOW;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RELEASE_PLAN_FLOW'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_PLAN_FLOW';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"
(
    "PLAN_FLOW_ID" NVARCHAR2(32) NOT NULL,
    "DELETED"      INTEGER NOT NULL,
    "PLAN_ID"      NVARCHAR2(255) NOT NULL,
    "PROJECT_CODE" NVARCHAR2(32) NOT NULL,
    "FLOW_CODE"    NVARCHAR2(128) NOT NULL,
    "FLOW_NAME"    NVARCHAR2(255),
    "FLOW_VERSION" NVARCHAR2(32) NOT NULL,
    "FLOW_SOURCE"  NVARCHAR2(2) NOT NULL,
    "CREATOR_ID"   NVARCHAR2(32),
    "CREATE_TIME"  DATE,
    "MODIFIER_ID"  NVARCHAR2(32),
    "UPDATE_TIME"  DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."PLAN_FLOW_ID" IS '迭代计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."PROJECT_CODE" IS '流程图所属项目code';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."FLOW_CODE" IS '流程 code';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."FLOW_NAME" IS '流程名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."FLOW_VERSION" IS '流程版本';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."FLOW_SOURCE" IS '流程类型, 01:依赖项目流程, 02:本项目流程';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."MODIFIER_ID" IS '更新人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_PLAN_FLOW" IS '发布计划流程图列表';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RELEASE_PLAN_FLOW
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_PLAN_FLOW
    ADD CONSTRAINT "PK_ERPF_PLANFLOWID_TNTID" PRIMARY KEY ("PLAN_FLOW_ID");


CREATE UNIQUE INDEX EASYFLOW_3052TJBHDEV."UK_ERPF_PPFF_D"
    ON EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_PLAN_FLOW ("PLAN_ID" ASC, "PROJECT_CODE" ASC, "FLOW_CODE" ASC, "FLOW_VERSION" ASC, "DELETED" ASC) TABLESPACE BASE;



-- ----------------------------
-- Table structure for EASYFLOW_RELEASE_UPGRADE;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RELEASE_UPGRADE'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_UPGRADE';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"
(
    "UPGRADE_ID"         NVARCHAR2(32) NOT NULL,
    "DELETED"            INTEGER NOT NULL,
    "PROJECT_CODE"       NVARCHAR2(32) NOT NULL,
    "ENV_CODE"           NVARCHAR2(32) NOT NULL,
    "CLUSTER_ID"         NVARCHAR2(255),
    "PLAN_ID"            NVARCHAR2(32) NOT NULL,
    "UPGRADE_TYPE"       NVARCHAR2(2) NOT NULL,
    "UPGRADE_STATUS"     NVARCHAR2(2) NOT NULL,
    "GRAY_FLUX_TYPE"     NVARCHAR2(2),
    "FLUX_GROUP_ID"      NVARCHAR2(255),
    "CONDITION_MODE"     NVARCHAR2(2),
    "GRAY_TOTAL_PERCENT" NUMBER(5,2),
    "REMARK"             NVARCHAR2(1024),
    "CREATOR_ID"         NVARCHAR2(32),
    "CREATE_TIME"        DATE,
    "MODIFIER_ID"        NVARCHAR2(32),
    "UPDATE_TIME"        DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."PROJECT_CODE" IS '项目编号';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."ENV_CODE" IS '环境编号';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."CLUSTER_ID" IS '集群id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."UPGRADE_TYPE" IS '升级方式,01 :直接升级,02:灰度升级';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."UPGRADE_STATUS" IS '升级状态,01:升级中,02:转正中,03:回滚中,04:回滚完成,05:转正完成,06:升级完成';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."GRAY_FLUX_TYPE" IS '灰度流控类型,01:按上下文内容,02:按流量比例';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."FLUX_GROUP_ID" IS '上下文规则组id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."CONDITION_MODE" IS '上下文规则,条件模式 01 all 02 any';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."GRAY_TOTAL_PERCENT" IS '灰度流量总百分比';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."REMARK" IS '备注';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."MODIFIER_ID" IS '更新人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE" IS '发布计划升级记录表';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RELEASE_UPGRADE
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_UPGRADE
    ADD CONSTRAINT "PK_ERU_UPGRADEID_TNTID" PRIMARY KEY ("UPGRADE_ID");



-- ----------------------------
-- Table structure for EASYFLOW_RELEASE_UPGRADE_LOG;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RELEASE_UPGRADE_LOG'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_UPGRADE_LOG';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"
(
    "LOG_ID"             NVARCHAR2(32) NOT NULL,
    "OP_ID"              NVARCHAR2(32),
    "OP_TIME"            DATE,
    "UPGRADE_ID"         NVARCHAR2(32) NOT NULL,
    "DELETED"            INTEGER NOT NULL,
    "PROJECT_CODE"       NVARCHAR2(32),
    "ENV_CODE"           NVARCHAR2(32) NOT NULL,
    "CLUSTER_ID"         NVARCHAR2(255),
    "PLAN_ID"            NVARCHAR2(32) NOT NULL,
    "PLAN_NAME"          NVARCHAR2(255),
    "UPGRADE_TYPE"       NVARCHAR2(2) NOT NULL,
    "UPGRADE_STATUS"     NVARCHAR2(2) NOT NULL,
    "GRAY_FLUX_TYPE"     NVARCHAR2(2),
    "FLUX_GROUP_ID"      NVARCHAR2(255),
    "CONDITION_MODE"     NVARCHAR2(2),
    "GRAY_TOTAL_PERCENT" NUMBER(5,2),
    "REMARK"             NVARCHAR2(1024),
    "CREATOR_ID"         NVARCHAR2(32),
    "CREATE_TIME"        DATE,
    "MODIFIER_ID"        NVARCHAR2(32),
    "UPDATE_TIME"        DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."LOG_ID" IS '日志id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."OP_ID" IS '操作人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."OP_TIME" IS '操作时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."UPGRADE_ID" IS '计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."PROJECT_CODE" IS '项目编号';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."ENV_CODE" IS '环境编号';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."CLUSTER_ID" IS '集群id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."PLAN_NAME" IS '发布计划名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."UPGRADE_TYPE" IS '升级方式,01 :直接升级,02:灰度升级';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."UPGRADE_STATUS" IS '升级状态,01:升级中,02:转正中,03:回滚中,04:回滚完成,05:转正完成,06:升级完成';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."GRAY_FLUX_TYPE" IS '灰度流控类型,01:按上下文内容,02:按流量比例';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."FLUX_GROUP_ID" IS '上下文规则组id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."CONDITION_MODE" IS '上下文规则,条件模式 01 all 02 any';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."GRAY_TOTAL_PERCENT" IS '灰度流量总百分比';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."REMARK" IS '备注';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."MODIFIER_ID" IS '更新人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RELEASE_UPGRADE_LOG" IS '版本配置操作日志';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RELEASE_UPGRADE_LOG
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RELEASE_UPGRADE_LOG
    ADD CONSTRAINT "PK_ERUL_LOGID_TNTID" PRIMARY KEY ("LOG_ID");

---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RP_BAK_API'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_API';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"
(
    "ID"                        NVARCHAR2(32) NOT NULL,
    "DELETED"                   INTEGER NOT NULL,
    "PLAN_ID"                   NVARCHAR2(32) NOT NULL,
    "UPGRADE_ID"                NVARCHAR2(32),
    "BACKUP_TYPE"               NVARCHAR2(2) NOT NULL,
    "PROJECT_CODE"              NVARCHAR2(32) NOT NULL,
    "EASYFLOW_API_HTTP_CONFIG"  NCLOB,
    "EASYFLOW_API_ROUTE_CONFIG" NCLOB,
    "EASYFLOW_DIRECTORY"        NCLOB,
    "CREATOR_ID"                NVARCHAR2(32),
    "CREATE_TIME"               DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."ID" IS 'id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."BACKUP_TYPE" IS '备份类型: 01:导入,02:升级前';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."EASYFLOW_API_HTTP_CONFIG" IS 'easyflow_api_http_config.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."EASYFLOW_API_ROUTE_CONFIG" IS 'easyflow_api_route_config.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."EASYFLOW_DIRECTORY" IS 'easyflow_directory.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API"."CREATE_TIME" IS '创建时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_API" IS '发布备份表API';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RP_BAK_API
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_API
    ADD CONSTRAINT "PK_ERBA_ID_TNTID" PRIMARY KEY ("ID");



-- ----------------------------
-- Table structure for EASYFLOW_RP_BAK_COMPONENT;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RP_BAK_COMPONENT'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_COMPONENT';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"
(
    "ID"                            NVARCHAR2(32) NOT NULL,
    "DELETED"                       INTEGER NOT NULL,
    "PLAN_ID"                       NVARCHAR2(32) NOT NULL,
    "UPGRADE_ID"                    NVARCHAR2(32),
    "BACKUP_TYPE"                   NVARCHAR2(2) NOT NULL,
    "PROJECT_CODE"                  NVARCHAR2(32) NOT NULL,
    "EASYFLOW_DIRECTORY"            NCLOB,
    "EASYFLOW_COMP_TEMPLATE_BASE"   NCLOB,
    "EASYFLOW_COMPONENT"            NCLOB,
    "EASYFLOW_EXCEP_CONF_TEMPLATE"  NCLOB,
    "EASYFLOW_SYSTEM_COMP_TEMPLATE" NCLOB,
    "EASYFLOW_RPC_COMP_TEMPLATE"    NCLOB,
    "CREATOR_ID"                    NVARCHAR2(32),
    "CREATE_TIME"                   DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."ID" IS 'id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."BACKUP_TYPE" IS '备份类型: 01:导入,02:升级前';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."EASYFLOW_DIRECTORY" IS 'easyflow_directory.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."EASYFLOW_COMP_TEMPLATE_BASE" IS 'easyflow_comp_template_base.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."EASYFLOW_COMPONENT" IS 'easyflow_component.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."EASYFLOW_EXCEP_CONF_TEMPLATE" IS 'easyflow_excep_conf_template.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."EASYFLOW_SYSTEM_COMP_TEMPLATE" IS 'easyflow_system_comp_template.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."EASYFLOW_RPC_COMP_TEMPLATE" IS 'easyflow_rpc_comp_template.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT"."CREATE_TIME" IS '创建时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_COMPONENT" IS '发布备份表component';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RP_BAK_COMPONENT
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_COMPONENT
    ADD CONSTRAINT "PK_ERBC_ID_TNTID" PRIMARY KEY ("ID");



-- ----------------------------
-- Table structure for EASYFLOW_RP_BAK_FLOW;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RP_BAK_FLOW'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FLOW';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"
(
    "ID"                          NVARCHAR2(32) NOT NULL,
    "DELETED"                     INTEGER NOT NULL,
    "PLAN_ID"                     NVARCHAR2(32) NOT NULL,
    "UPGRADE_ID"                  NVARCHAR2(32),
    "BACKUP_TYPE"                 NVARCHAR2(2) NOT NULL,
    "PROJECT_CODE"                NVARCHAR2(32) NOT NULL,
    "EASYFLOW_DIRECTORY"          NCLOB,
    "EASYFLOW_ELEMENT_CHANGE_REC" NCLOB,
    "EASYFLOW_FLOW_COMMIT_REC"    NCLOB,
    "EASYFLOW_FLOW_DEFINE"        NCLOB,
    "EASYFLOW_FLOW_DETAIL_REC"    NCLOB,
    "EASYFLOW_FLOW_RELATION"      NCLOB,
    "EASYFLOW_FLOW_RELEASE_REC"   NCLOB,
    "EASYFLOW_LOCAL_TX_DEFINE"    NCLOB,
    "CREATOR_ID"                  NVARCHAR2(32),
    "CREATE_TIME"                 DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."ID" IS 'id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."BACKUP_TYPE" IS '备份类型: 01:导入,02:升级前';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."EASYFLOW_DIRECTORY" IS 'easyflow_directory.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."EASYFLOW_ELEMENT_CHANGE_REC" IS 'easyflow_element_change_rec.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."EASYFLOW_FLOW_COMMIT_REC" IS 'easyflow_flow_commit_rec.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."EASYFLOW_FLOW_DEFINE" IS 'easyflow_flow_define.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."EASYFLOW_FLOW_DETAIL_REC" IS 'easyflow_flow_detail_rec.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."EASYFLOW_FLOW_RELATION" IS 'easyflow_flow_relation.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."EASYFLOW_FLOW_RELEASE_REC" IS 'easyflow_flow_release_rec.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."EASYFLOW_LOCAL_TX_DEFINE" IS 'easyflow_local_tx_define.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW"."CREATE_TIME" IS '创建时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW" IS '发布备份表 FLOW';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RP_BAK_FLOW
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FLOW
    ADD CONSTRAINT "PK_ERBF_ID_TNTID" PRIMARY KEY ("ID");



-- ----------------------------
-- Table structure for EASYFLOW_RP_BAK_FLOW_DD;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RP_BAK_FLOW_DD'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FLOW_DD';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"
(
    "ID"                 NVARCHAR2(32) NOT NULL,
    "DELETED"            INTEGER NOT NULL,
    "PLAN_ID"            NVARCHAR2(32) NOT NULL,
    "UPGRADE_ID"         NVARCHAR2(32),
    "BACKUP_TYPE"        NVARCHAR2(2) NOT NULL,
    "PROJECT_CODE"       NVARCHAR2(32) NOT NULL,
    "FLOW_DETAIL_ID"     NVARCHAR2(32) NOT NULL,
    "FLOW_DETAIL_DEFINE" NCLOB,
    "CREATOR_ID"         NVARCHAR2(32),
    "CREATE_TIME"        DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."ID" IS 'id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."BACKUP_TYPE" IS '备份类型: 01:导入,02:升级前';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."FLOW_DETAIL_ID" IS '流程版本id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."FLOW_DETAIL_DEFINE" IS '单条 easyflow_flow_detail_define.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD"."CREATE_TIME" IS '创建时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DD" IS '发布备份表 detail_define';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RP_BAK_FLOW_DD
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FLOW_DD
    ADD CONSTRAINT "PK_ERBFD_ID_TNTID" PRIMARY KEY ("ID");



-- ----------------------------
-- Table structure for EASYFLOW_RP_BAK_FLOW_DEPLOY;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RP_BAK_FLOW_DEPLOY'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FLOW_DEPLOY';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"
(
    "ID"           NVARCHAR2(32) NOT NULL,
    "DELETED"      INTEGER NOT NULL,
    "PLAN_ID"      NVARCHAR2(32) NOT NULL,
    "UPGRADE_ID"   NVARCHAR2(32) NOT NULL,
    "BACKUP_TYPE"  NVARCHAR2(2) NOT NULL,
    "PROJECT_CODE" NVARCHAR2(32) NOT NULL,
    "FLOW_CODE"    NVARCHAR2(32) NOT NULL,
    "FLOW_VERSION" NVARCHAR2(32) NOT NULL,
    "CREATOR_ID"   NVARCHAR2(32),
    "CREATE_TIME"  DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."ID" IS 'id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."BACKUP_TYPE" IS '备份类型: 02:升级前';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."FLOW_CODE" IS '流程编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."FLOW_VERSION" IS '流程版本';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."CREATE_TIME" IS '创建时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY" IS '发布备份表 FLOW当前部署记录';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RP_BAK_FLOW_DEPLOY
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FLOW_DEPLOY
    ADD CONSTRAINT "PK_ERBFD_DEPLOY_ID_TNTID" PRIMARY KEY ("ID");



-- ----------------------------
-- Table structure for EASYFLOW_RP_BAK_FLOW_RC;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RP_BAK_FLOW_RC'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FLOW_RC';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"
(
    "ID"                 NVARCHAR2(32) NOT NULL,
    "DELETED"            INTEGER NOT NULL,
    "PLAN_ID"            NVARCHAR2(32) NOT NULL,
    "UPGRADE_ID"         NVARCHAR2(32),
    "BACKUP_TYPE"        NVARCHAR2(2) NOT NULL,
    "PROJECT_CODE"       NVARCHAR2(32) NOT NULL,
    "FLOW_DETAIL_ID"     NVARCHAR2(32) NOT NULL,
    "FLOW_RELEASE_CHART" NCLOB,
    "CREATOR_ID"         NVARCHAR2(32),
    "CREATE_TIME"        DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."ID" IS 'id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."BACKUP_TYPE" IS '备份类型: 01:导入,02:升级前';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."FLOW_DETAIL_ID" IS '流程版本id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."FLOW_RELEASE_CHART" IS '单条 easyflow_flow_release_chart.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC"."CREATE_TIME" IS '创建时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_RC" IS '发布备份表 release_chart';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RP_BAK_FLOW_RC
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FLOW_RC
    ADD CONSTRAINT "PK_ERBFR_ID_TNTID" PRIMARY KEY ("ID");



-- ----------------------------
-- Table structure for EASYFLOW_RP_BAK_FUNCTION;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RP_BAK_FUNCTION'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FUNCTION';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"
(
    "ID"                     NVARCHAR2(32) NOT NULL,
    "DELETED"                INTEGER NOT NULL,
    "PLAN_ID"                NVARCHAR2(32) NOT NULL,
    "UPGRADE_ID"             NVARCHAR2(32),
    "BACKUP_TYPE"            NVARCHAR2(2) NOT NULL,
    "PROJECT_CODE"           NVARCHAR2(32) NOT NULL,
    "EASYFLOW_DIRECTORY"     NCLOB,
    "EASYFLOW_RULE_FUNCTION" NCLOB,
    "CREATOR_ID"             NVARCHAR2(32),
    "CREATE_TIME"            DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."ID" IS 'id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."BACKUP_TYPE" IS '备份类型: 01:导入,02:升级前';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."EASYFLOW_DIRECTORY" IS 'easyflow_directory.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."EASYFLOW_RULE_FUNCTION" IS 'easyflow_rule_function.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION"."CREATE_TIME" IS '创建时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FUNCTION" IS '发布备份表function';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RP_BAK_FUNCTION
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_FUNCTION
    ADD CONSTRAINT "PK_ERBF_FUNCTION_ID_TNTID" PRIMARY KEY ("ID");



-- ----------------------------
-- Table structure for EASYFLOW_RP_BAK_RULE;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RP_BAK_RULE'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_RULE';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"
(
    "ID"                   NVARCHAR2(32) NOT NULL,
    "DELETED"              INTEGER NOT NULL,
    "PLAN_ID"              NVARCHAR2(32) NOT NULL,
    "UPGRADE_ID"           NVARCHAR2(32),
    "BACKUP_TYPE"          NVARCHAR2(2) NOT NULL,
    "PROJECT_CODE"         NVARCHAR2(32) NOT NULL,
    "EASYFLOW_DIRECTORY"   NCLOB,
    "EASYFLOW_RULE_DEFINE" NCLOB,
    "EASYFLOW_RULE_PARAM"  NCLOB,
    "CREATOR_ID"           NVARCHAR2(32),
    "CREATE_TIME"          DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."ID" IS 'id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."PLAN_ID" IS '发布计划id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."UPGRADE_ID" IS '升级记录id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."BACKUP_TYPE" IS '备份类型: 01:导入,02:升级前';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."EASYFLOW_DIRECTORY" IS 'easyflow_directory.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."EASYFLOW_RULE_DEFINE" IS 'easyflow_comp_template_base.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."EASYFLOW_RULE_PARAM" IS 'easyflow_component.json';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE"."CREATE_TIME" IS '创建时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_RULE" IS '发布备份表rule';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RP_BAK_RULE
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RP_BAK_RULE
    ADD CONSTRAINT "PK_ERBR_ID_TNTID" PRIMARY KEY ("ID");



-- ----------------------------
-- Table structure for EASYFLOW_RPC_COMP_TEMPLATE;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_RPC_COMP_TEMPLATE'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_RPC_COMP_TEMPLATE';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"
(
    "ID"                     NVARCHAR2(32) NOT NULL,
    "INTERFACE_NAME"         NVARCHAR2(255) NOT NULL,
    "METHOD_NAME"            NVARCHAR2(32) NOT NULL,
    "INTERFACE_MEMO"         NVARCHAR2(255),
    "METHOD_MEMO"            NVARCHAR2(255),
    "IN_PARAMETER"           NCLOB,
    "OUT_PARAMETER"          NCLOB,
    "EXCEPTION_CONF"         NCLOB,
    "PENDING"                INTEGER,
    "PENDING_RETURN_CONF"    NCLOB,
    "PENDING_CALL_BACK_CONF" NCLOB,
    "CREATE_TIME"            DATE,
    "UPDATE_TIME"            DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."ID" IS '主键ID';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."INTERFACE_NAME" IS 'rpc接口名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."METHOD_NAME" IS '方法名';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."INTERFACE_MEMO" IS '接口说明';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."METHOD_MEMO" IS '方法说明';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."IN_PARAMETER" IS '入参配置';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."OUT_PARAMETER" IS '出参配置';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."EXCEPTION_CONF" IS '异常配置';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."PENDING" IS '是否正常挂起(0-不挂起，1-挂起)';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."PENDING_RETURN_CONF" IS '正常挂起返回配置';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."PENDING_CALL_BACK_CONF" IS '正常挂起回调配置';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_RPC_COMP_TEMPLATE" IS 'rpc组件模板信息表';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_RPC_COMP_TEMPLATE
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_RPC_COMP_TEMPLATE
    ADD CONSTRAINT "PK_ERCT_ID_TNTID" PRIMARY KEY ("ID");
---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_SERVICE_INFO'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_SERVICE_INFO';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"
(
    "SERVICE_INFO_ID"    NVARCHAR2(32) NOT NULL,
    "DELETED"            INTEGER NOT NULL,
    "SERVICE_NAME"       NVARCHAR2(64) NOT NULL,
    "SERVICE_VERSION"    NVARCHAR2(64) NOT NULL,
    "MEMORY_HEAP_SIZE"   INTEGER,
    "MAIN_ARGS"          NVARCHAR2(128),
    "REFER_STARTUP_TIME" INTEGER,
    "LOCAL_JAR_PATH"     NVARCHAR2(128) NOT NULL,
    "REMOTE_JAR_URL"     NVARCHAR2(1024) NOT NULL,
    "CHECKSUM_SHA1"      NVARCHAR2(64),
    "CHECKSUM_MD5"       NVARCHAR2(64),
    "CLASS_ANNOTATION"   NVARCHAR2(512),
    "METHOD_ANNOTATION"  NVARCHAR2(512),
    "AOP_EXECUTION"      NVARCHAR2(512),
    "PROJECT_CODE"       NVARCHAR2(32) NOT NULL,
    "CREATOR_ID"         NVARCHAR2(32),
    "CREATE_TIME"        DATE,
    "MODIFIER_ID"        NVARCHAR2(32),
    "UPDATE_TIME"        DATE,
    "SCAN_TYPE"          INTEGER
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."SERVICE_INFO_ID" IS '服务信息id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."SERVICE_NAME" IS '服务名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."SERVICE_VERSION" IS '服务版本';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."MEMORY_HEAP_SIZE" IS '堆内存预估设置';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."MAIN_ARGS" IS '启动方法参数';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."REFER_STARTUP_TIME" IS '参考启动时间(秒)';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."LOCAL_JAR_PATH" IS '本地jar路径';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."REMOTE_JAR_URL" IS '远端jar路径';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."CHECKSUM_SHA1" IS 'sha1_checksum';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."CHECKSUM_MD5" IS 'md5_checksum';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."CLASS_ANNOTATION" IS '类注解';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."METHOD_ANNOTATION" IS '方法注解';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."AOP_EXECUTION" IS '切面表达式';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."PROJECT_CODE" IS '项目编码';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."MODIFIER_ID" IS '更新人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO"."SCAN_TYPE" IS '组件扫描配置维度  1注解 2 切面 3 注解+切面';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_INFO" IS '服务信息表 ';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_SERVICE_INFO
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_SERVICE_INFO
    ADD CONSTRAINT "PK_ESI_SERVICEINFOID_TNTID" PRIMARY KEY ("SERVICE_INFO_ID");


CREATE UNIQUE INDEX EASYFLOW_3052TJBHDEV."SERVICE_NAME_VERSION_DELETED"
    ON EASYFLOW_3052TJBHDEV.EASYFLOW_SERVICE_INFO ("SERVICE_NAME" ASC, "SERVICE_VERSION" ASC, "DELETED" ASC) TABLESPACE BASE;



-- ----------------------------
-- Table structure for EASYFLOW_SERVICE_VERSION;
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_SERVICE_VERSION'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_SERVICE_VERSION';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"
(
    "SERVICE_VERSION_ID"     NVARCHAR2(32) NOT NULL,
    "DELETED"                INTEGER NOT NULL,
    "PROJECT_CODE"           NVARCHAR2(32) NOT NULL,
    "ENV_CODE"               NVARCHAR2(32) NOT NULL,
    "CLUSTER_ID"             NVARCHAR2(255) NOT NULL,
    "SERVICE_NAME"           NVARCHAR2(512) NOT NULL,
    "SERVICE_VERSION"        NVARCHAR2(64) NOT NULL,
    "VERSION_STATUS"         NVARCHAR2(2) NOT NULL,
    "EXPECTED_COUNT" INTEGER DEFAULT (0),
    "ACTUATOR_VERSION"       NVARCHAR2(64),
    "CREATOR_ID"             NVARCHAR2(32),
    "CREATE_TIME"            DATE,
    "MODIFIER_ID"            NVARCHAR2(32),
    "UPDATE_TIME"            DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."SERVICE_VERSION_ID" IS '依赖信息id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."DELETED" IS '逻辑删除';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."PROJECT_CODE" IS '项目编号';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."ENV_CODE" IS '环境编号';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."CLUSTER_ID" IS '集群id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."SERVICE_NAME" IS '服务名,easyflow-dispatcher';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."SERVICE_VERSION" IS '服务版本';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."VERSION_STATUS" IS '版本状态, 01:静默,02:备份,03:活动';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."EXPECTED_COUNT" IS '期望节点数,期望进程数';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."ACTUATOR_VERSION" IS '执行器版本';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."CREATOR_ID" IS '创建人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."MODIFIER_ID" IS '更新人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_SERVICE_VERSION" IS '服务版本配置表';



-- ----------------------------
-- Primary Key structure for table EASYFLOW_SERVICE_VERSION
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_SERVICE_VERSION
    ADD CONSTRAINT "PK_ESV_SERVICEVERSIONID_TNTID" PRIMARY KEY ("SERVICE_VERSION_ID");


CREATE UNIQUE INDEX EASYFLOW_3052TJBHDEV."UK_ESV_PECSS_D"
    ON EASYFLOW_3052TJBHDEV.EASYFLOW_SERVICE_VERSION ("PROJECT_CODE" ASC, "ENV_CODE" ASC, "CLUSTER_ID" ASC, "SERVICE_NAME" ASC, "SERVICE_VERSION" ASC, "DELETED" ASC) TABLESPACE BASE;

---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_SHUTDOWN_LOG'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_SHUTDOWN_LOG';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"
(
    "LOG_ID"       NVARCHAR2(32) NOT NULL,
    "LOG_TYPE"     NVARCHAR2(2) NOT NULL,
    "OP_ID"        NVARCHAR2(32),
    "OP_TIME"      DATE,
    "PROJECT_CODE" NVARCHAR2(32) NOT NULL,
    "ENV_CODE"     NVARCHAR2(32) NOT NULL,
    "CLUSTER_ID"   NVARCHAR2(255),
    "NODE_ID"      NVARCHAR2(512),
    "NODE_ADDRESS" NVARCHAR2(512),
    "NODE_STATUS"  NVARCHAR2(2),
    "CREATE_TIME"  DATE,
    "UPDATE_TIME"  DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."LOG_ID" IS '日志id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."LOG_TYPE" IS '01 停机记录, 02 停用记录, 03 启用记录';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."OP_ID" IS '操作人';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."OP_TIME" IS '操作时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."PROJECT_CODE" IS '项目名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."ENV_CODE" IS '环境编号';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."CLUSTER_ID" IS '集群id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."NODE_ID" IS '节点id,调度器,执行器';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."NODE_ADDRESS" IS '节点地址';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."NODE_STATUS" IS '节点状态';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_SHUTDOWN_LOG" IS '停机操作日志表';

/*
 * yunrong.cn Inc. Copyright (c) 2014-2022 All Rights Reserved
 */

-- ----------------------------
-- Primary Key structure for table EASYFLOW_SHUTDOWN_LOG
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV.EASYFLOW_SHUTDOWN_LOG
    ADD CONSTRAINT "PK_ESL_LOGID_TNTID" PRIMARY KEY ("LOG_ID");



ALTER TABLE "EASYFLOW_3052TJBHDEV".EASYFLOW_RELEASE_PLAN
    ADD TRACE_PLAN_ID NVARCHAR2(32) NULL;
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV".EASYFLOW_RELEASE_PLAN.TRACE_PLAN_ID IS '追溯计划id';

-- 添加操作动作和灰度规则上下文内容字段

ALTER TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_RELEASE_UPGRADE_LOG"
    ADD (OP_ACTION NVARCHAR2(64) NULL,FLUX_CONTEXT NCLOB NULL);
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_RELEASE_UPGRADE_LOG".OP_ACTION IS '操作动作';
COMMENT ON COLUMN "EASYFLOW_3052TJBHDEV"."EASYFLOW_RELEASE_UPGRADE_LOG".FLUX_CONTEXT IS '灰度规则上下文内容';

-- fix JSPT-578
DELETE FROM "EASYFLOW_3052TJBHDEV"."EASYFLOW_PROJECT_USER_ROLE_REL" WHERE (PROJECT_CODE, USER_ID, ROLE_ID)
    IN
                                                              (SELECT PROJECT_CODE, USER_ID, ROLE_ID FROM (SELECT PROJECT_CODE, USER_ID, ROLE_ID FROM "EASYFLOW_3052TJBHDEV"."EASYFLOW_PROJECT_USER_ROLE_REL" GROUP BY PROJECT_CODE, USER_ID, ROLE_ID HAVING COUNT(*)>1) S1)
                                                          AND
        USER_ROLE_REL_ID NOT IN (SELECT USER_ROLE_REL_ID FROM (SELECT MAX(USER_ROLE_REL_ID) USER_ROLE_REL_ID,PROJECT_CODE, USER_ID, ROLE_ID FROM "EASYFLOW_3052TJBHDEV"."EASYFLOW_PROJECT_USER_ROLE_REL" GROUP BY PROJECT_CODE, USER_ID, ROLE_ID HAVING COUNT(*)>1) S2);

CREATE UNIQUE INDEX UK_EPURR_PUR ON EASYFLOW_PROJECT_USER_ROLE_REL (PROJECT_CODE, USER_ID, ROLE_ID) ;

/**
 * 01.scripts/1.2/1.2.3.5/easyflow-admin-oracle-1.2.3.5-ddl-iteration3.sql
 * */
-- ----------------------------
-- 更新时间：2022/02/16
-- 负责人：李仁会
-- 更新内容：流程定义信息表修改
-- ----------------------------

UPDATE "EASYFLOW_3052TJBHDEV"."EASYFLOW_FLOW_DEFINE"
SET BIZ_TYPE = '01'
WHERE BIZ_TYPE = ''
   OR BIZ_TYPE IS NULL;

ALTER TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_FLOW_DEFINE"
    MODIFY (BIZ_TYPE DEFAULT '01' NOT NULL);

ALTER TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_API_ROUTE_CONFIG" DROP COLUMN "API_BIZ_TYPE";

-- ----------------------------
-- 更新时间：2022/03/25
-- 负责人：蔡锦堂
-- 更新内容：发布备份表修改字段长度
-- ----------------------------
ALTER TABLE "EASYFLOW_3052TJBHDEV"."EASYFLOW_RP_BAK_FLOW_DEPLOY"
    MODIFY (FLOW_CODE NVARCHAR2(128));
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_RP_BAK_FLOW_DEPLOY"."FLOW_CODE" IS '流程编号';

-- ----------------------------
-- 更新时间：2022/04/13
-- 负责人：蔡锦堂
-- 更新内容：流程环境关系表，唯一索引状态新增
-- ----------------------------
DROP INDEX UK_FER_FC_PE;
CREATE UNIQUE INDEX UK_FER_FC_PEW ON EASYFLOW_FLOW_ENV_RELATION (PROJECT_CODE, FLOW_CODE, DEPLOYED_PROJECT_CODE, DEPLOYED_ENV_CODE, WORK_STATUS);

DROP INDEX UK_FER_FI_PE;
CREATE UNIQUE INDEX UK_FER_FI_PEW ON EASYFLOW_FLOW_ENV_RELATION (FLOW_ID, DEPLOYED_PROJECT_CODE, DEPLOYED_ENV_CODE, WORK_STATUS);

DROP INDEX UK_FER_FI_EI;
CREATE UNIQUE INDEX UK_FER_FI_EIW ON EASYFLOW_FLOW_ENV_RELATION (FLOW_ID, DEPLOYED_ENV_ID, WORK_STATUS);


/**
 * 01.scripts/1.2/1.2.3.6/easyflow-admin-oracle-1.2.3.6-ddl-iteration.sql
 * */
-- ----------------------------
-- 更新时间：2022-03-18
-- 负责人：叶吕楸
-- 更新内容：环境服务名称映射配置 表结构
-- ----------------------------
-- 1. 环境服务名称映射配置
declare
    num number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_ENV_SERVICE_MAPPING'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
        num = 1 then
        execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_ENV_SERVICE_MAPPING';
end if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"
(
    "SERVICE_MAPPING_ID"  NVARCHAR2(32)  NOT NULL,
    "PARENT_PROJECT_CODE" NVARCHAR2(128) NOT NULL,
    "PROJECT_CODE"        NVARCHAR2(128) NOT NULL,
    "ENV_CODE"            NVARCHAR2(128) NOT NULL,
    "ENV_ID"              NVARCHAR2(32)  NOT NULL,
    "CLUSTER_ID"          NVARCHAR2(64),
    "ORIGIN_SERVICE_NAME" NVARCHAR2(64)  NOT NULL,
    "TARGET_SERVICE_NAME" NVARCHAR2(64),
    "CREATE_TIME"         DATE           NOT NULL,
    "UPDATE_TIME"         DATE           NOT NULL
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."SERVICE_MAPPING_ID" IS '主键 服务名映射 ID';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."PARENT_PROJECT_CODE" IS '父项目 code';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."PROJECT_CODE" IS '项目 code';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."ENV_CODE" IS '环境编号';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."ENV_ID" IS '环境ID';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."CLUSTER_ID" IS '集群ID';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."ORIGIN_SERVICE_NAME" IS '原服务名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."TARGET_SERVICE_NAME" IS '映射服务名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING"."UPDATE_TIME" IS '更新时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_ENV_SERVICE_MAPPING" IS '环境服务名称映射配置';
-- ----------------------------
-- 更新时间：2022-03-19
-- 负责人：蔡锦堂
-- 更新内容：流程定义表新增图类型
-- ----------------------------
ALTER TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_FLOW_DEFINE"
    ADD FLOW_DEFINE_TYPE NVARCHAR2(2) NOT NULL;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLOW_DEFINE"."FLOW_DEFINE_TYPE" IS '流程定义类型，01-普通，02-环节';


-- ----------------------------
-- 更新时间：2022-03-19
-- 负责人：李杰
-- 更新内容：组件标签信息表
-- ----------------------------
declare
num   number;
begin
select count(1)
           into num
from all_tables
where TABLE_NAME = 'EASYFLOW_TAG_INFO'
  and OWNER = 'EASYFLOW_3052TJBHDEV';
if
num=1   then
         execute immediate 'drop table EASYFLOW_3052TJBHDEV.EASYFLOW_TAG_INFO';
end   if;
end;
/
CREATE TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"
(
    "TAG_ID"       NVARCHAR2(64) NOT NULL,
    "TAG_NAME"     NVARCHAR2(32) NOT NULL,
    "TAG_LEVEL"    INTEGER NOT NULL,
    "PROJECT_CODE" NVARCHAR2(64),
    "DIRECTORY_ID" NVARCHAR2(64),
    "PARENT_ID"    NVARCHAR2(64),
    "FULL_ID_PATH" NCLOB   NOT NULL,
    "CREATE_TIME"  DATE,
    "UPDATE_TIME"  DATE
) TABLESPACE BASE
;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."TAG_ID" IS '主键, tagLevel.tagName';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."TAG_NAME" IS '标签名称';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."TAG_LEVEL" IS '标签级别';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."PROJECT_CODE" IS '项目编码,可空';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."DIRECTORY_ID" IS '目录ID,可空';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."PARENT_ID" IS '父级标签id';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."FULL_ID_PATH" IS '';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."CREATE_TIME" IS '创建时间';
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO"."UPDATE_TIME" IS '修改时间';
COMMENT
    ON TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_TAG_INFO" IS '标签信息表';


CREATE UNIQUE INDEX PRIMARY ON EASYFLOW_3052TJBHDEV.EASYFLOW_TAG_INFO (TAG_ID);
CREATE UNIQUE INDEX UX_ETI_FIP ON EASYFLOW_3052TJBHDEV.EASYFLOW_TAG_INFO (FULL_ID_PATH);
CREATE UNIQUE INDEX UX_ETI_TN_TL ON EASYFLOW_3052TJBHDEV.EASYFLOW_TAG_INFO (TAG_NAME, TAG_LEVEL);



ALTER TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_COMPONENT"
    ADD TAGS NCLOB NULL;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_COMPONENT"."TAGS" IS '关联的 tagFullPath Set JSONArray';


ALTER TABLE EASYFLOW_3052TJBHDEV."EASYFLOW_FLOW_DETAIL_REC"
    ADD FLOW_NORMAL_RUN_MARKER NVARCHAR2(256) NULL;
COMMENT
    ON COLUMN EASYFLOW_3052TJBHDEV."EASYFLOW_FLOW_DETAIL_REC"."FLOW_NORMAL_RUN_MARKER" IS '流程正常执行标识，使用字符逗号拼接，支持多个版本，例如V1,V2';








